export const DEFINIR_PRODUTOS = 'DEFINIR_PRODUTOS';
export const REMOVER_PRODUTO = 'REMOVER_PRODUTO';
export const ATUALIZAR_PRODUTO = 'ATUALIZAR_PRODUTO';
export const ACRESCENTAR_PRODUTO = 'ACRESCENTAR_PRODUTO';
