export const DEFINIR_PRODUTOS = 'DEFINIR_PRODUTOS';
export const REMOVER_PRODUTO = 'REMOVER_PRODUTO';
export const ATUALIZAR_PRODUTO = 'ATUALIZAR_PRODUTO';
export const ACRESCENTAR_PRODUTO = 'ACRESCENTAR_PRODUTO';
export const DEFINIR_PEDIDOS = 'DEFINIR_PEDIDOS';
export const REMOVER_PEDIDO = 'REMOVER_PEDIDO';
export const ATUALIZAR_PEDIDO = 'ATUALIZAR_PEDIDO';
export const ACRESCENTAR_PEDIDO = 'ACRESCENTAR_PEDIDO';
